// ---------------------------------------------------------------------------
// TIGI AI Valuation — Type definitions.
//
// These types represent the full output of the TIGI valuation engine.
// MVP: populated with mock structured data.
// Production: generated by the ValuationService (ML model + comparables DB).
//
// The shape is intentionally stable — consumers (badge, panel) don't change
// when the data source swaps from mock → real service.
// ---------------------------------------------------------------------------

export type AiConfidence = 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH'

/** Which direction a value driver pushes the estimate */
export type DriverDirection = 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL'

/** How strongly the driver influences the final estimate */
export type DriverImpact = 'HIGH' | 'MEDIUM' | 'LOW'

/** A single factor that influenced the AI estimate */
export interface ValuationDriver {
  label: string              // "Location premium"
  description: string        // "Above-median walkability score, South Austin 78704"
  direction: DriverDirection
  impact: DriverImpact
}

/** Low / mid / high confidence interval around the estimate */
export interface ValuationRange {
  low: number                // Conservative floor (e.g. -10%)
  mid: number                // Central estimate — matches estimatedValue
  high: number               // Optimistic ceiling (e.g. +10%)
}

/** A comparable sale used to inform the estimate */
export interface ValuationComparable {
  address: string            // "123 Oak St, Austin TX"
  soldPrice: number
  soldDate: string           // "Jan 2026"
  // Property-specific
  sqft?: number
  pricePerSqft?: number
  // Land-specific
  acres?: number
  pricePerAcre?: number
  // Similarity score (0–100) for display
  similarityScore: number
}

/** Full structured output of a valuation run */
export interface AiValuation {
  listingId: string
  assetType: 'property' | 'land'
  estimatedValue: number
  confidence: AiConfidence
  range: ValuationRange
  drivers: ValuationDriver[]      // 3–5 drivers, ordered by impact
  comparables: ValuationComparable[]  // 2–3 recent comps
  modelVersion: string            // e.g. "tigi-val-v0.2-mock"
  generatedAt: string             // ISO 8601
  methodology: string             // Short human-readable description
}

// ---------------------------------------------------------------------------
// Confidence display config — single source of truth used by badge + panel
// ---------------------------------------------------------------------------

export const CONFIDENCE_CONFIG: Record<
  AiConfidence,
  { label: string; shortLabel: string; color: string; barWidth: string; ringClass: string }
> = {
  VERY_HIGH: {
    label: 'Very High Confidence',
    shortLabel: 'Very High',
    color: '#4ADE80',
    barWidth: '100%',
    ringClass: 'ring-[#22C55E]/30 bg-[#22C55E]/10 text-[#4ADE80]',
  },
  HIGH: {
    label: 'High Confidence',
    shortLabel: 'High',
    color: '#86EFAC',
    barWidth: '80%',
    ringClass: 'ring-[#22C55E]/25 bg-[#22C55E]/8 text-[#86EFAC]',
  },
  MEDIUM: {
    label: 'Medium Confidence',
    shortLabel: 'Medium',
    color: '#FCD34D',
    barWidth: '55%',
    ringClass: 'ring-[#F59E0B]/25 bg-[#F59E0B]/8 text-[#FCD34D]',
  },
  LOW: {
    label: 'Low Confidence',
    shortLabel: 'Low',
    color: '#6B6B80',
    barWidth: '30%',
    ringClass: 'ring-[#3A3A48] bg-[#2A2A3A]/50 text-[#6B6B80]',
  },
}

// ---------------------------------------------------------------------------
// Driver display config
// ---------------------------------------------------------------------------

export const DIRECTION_CONFIG: Record<
  DriverDirection,
  { symbol: string; color: string; bg: string }
> = {
  POSITIVE: { symbol: '▲', color: '#4ADE80', bg: 'rgba(74,222,128,0.08)' },
  NEGATIVE: { symbol: '▼', color: '#F87171', bg: 'rgba(248,113,113,0.08)' },
  NEUTRAL:  { symbol: '─', color: '#6B6B80', bg: 'rgba(107,107,128,0.08)' },
}

export const IMPACT_LABEL: Record<DriverImpact, string> = {
  HIGH:   'Strong',
  MEDIUM: 'Moderate',
  LOW:    'Minor',
}
