// ---------------------------------------------------------------------------
// Marketplace mock data — structured to mirror the future Prisma schema.
// Replacing this with real DB queries = swap MOCK_LISTINGS for a prisma call.
// ---------------------------------------------------------------------------

export type PropertyType = 'RESIDENTIAL' | 'COMMERCIAL' | 'LAND' | 'INDUSTRIAL' | 'MIXED_USE'
export type ListingType = 'BUY' | 'LEASE' | 'BOTH'
export type ListingStatus = 'ACTIVE' | 'SOLD' | 'LEASED' | 'UNDER_REVIEW'
export type AiConfidence = 'LOW' | 'MEDIUM' | 'HIGH'
export type ImagePropertyType = 'residential' | 'commercial' | 'land' | 'industrial' | 'mixed'

export interface MockListing {
  id: string
  title: string
  description: string
  propertyType: PropertyType
  listingType: ListingType
  status: ListingStatus
  price: number
  city: string
  state: string
  sqft: number
  bedrooms: number | null
  bathrooms: number | null
  yearBuilt: number | null
  lotAcres: number | null
  features: string[]
  // Token info
  isTokenized: boolean
  tokenTotalSupply: number | null
  tokenAvailableSupply: number | null
  tokenPricePerFraction: number | null
  tokenInvestorCount: number | null
  // Image — real URL takes priority; falls back to placeholder slot
  // Optional: mock data omits this; DB-backed listings populate it.
  imageUrl?: string | null
  imageSlot: string
  imagePropertyType: ImagePropertyType
  // Meta
  createdAt: string
  viewCount: number
  // AI valuation (MockValuationService — real model plugs in at M6)
  aiEstimatedValue: number | null
  aiConfidence: AiConfidence | null
}

export const MOCK_LISTINGS: MockListing[] = [
  // ── RESIDENTIAL ────────────────────────────────────────────────────────────
  {
    id: 'res-001',
    title: 'Westside Craftsman Bungalow',
    description: 'Beautifully restored 1920s craftsman with original hardwood floors, updated kitchen, and a landscaped backyard. Walkable to restaurants and parks in South Austin.',
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 485000,
    city: 'Austin',
    state: 'TX',
    sqft: 1840,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 1924,
    lotAcres: 0.18,
    features: ['Hardwood floors', 'Updated kitchen', 'Covered porch', 'Fenced yard'],
    isTokenized: true,
    tokenTotalSupply: 500,
    tokenAvailableSupply: 210,
    tokenPricePerFraction: 970,
    tokenInvestorCount: 18,
    imageSlot: 'residential-1',
    imagePropertyType: 'residential',
    createdAt: '2026-03-01',
    viewCount: 1247,
    aiEstimatedValue: 492000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'res-002',
    title: 'Midtown Modern Townhome',
    description: "Three-story contemporary townhome in Atlanta's most desirable Midtown neighborhood. Rooftop terrace with skyline views, private garage, chef's kitchen with waterfall island.",
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 620000,
    city: 'Atlanta',
    state: 'GA',
    sqft: 2240,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2019,
    lotAcres: 0.08,
    features: ['Rooftop terrace', 'Skyline views', 'Private garage', 'Smart home'],
    isTokenized: true,
    tokenTotalSupply: 1000,
    tokenAvailableSupply: 280,
    tokenPricePerFraction: 620,
    tokenInvestorCount: 34,
    imageSlot: 'residential-2',
    imagePropertyType: 'residential',
    createdAt: '2026-02-22',
    viewCount: 2081,
    aiEstimatedValue: 635000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'res-003',
    title: 'Coastal Villa with Ocean Views',
    description: 'Exceptional oceanfront villa with panoramic Atlantic views, private pool, and direct beach access. Five-bedroom retreat in an exclusive Miami Beach enclave.',
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 1250000,
    city: 'Miami Beach',
    state: 'FL',
    sqft: 3800,
    bedrooms: 5,
    bathrooms: 4,
    yearBuilt: 2015,
    lotAcres: 0.32,
    features: ['Ocean views', 'Private pool', 'Beach access', 'Guest house'],
    isTokenized: true,
    tokenTotalSupply: 1000,
    tokenAvailableSupply: 350,
    tokenPricePerFraction: 1250,
    tokenInvestorCount: 56,
    imageSlot: 'residential-3',
    imagePropertyType: 'residential',
    createdAt: '2026-02-14',
    viewCount: 4320,
    aiEstimatedValue: 1190000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'res-004',
    title: 'Highland Park Colonial Estate',
    description: "Grand colonial on one of Dallas's most prestigious streets. Formal dining, library, updated primary suite, pool and cabana. Premier school district.",
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 895000,
    city: 'Dallas',
    state: 'TX',
    sqft: 4200,
    bedrooms: 5,
    bathrooms: 4,
    yearBuilt: 1985,
    lotAcres: 0.45,
    features: ['Pool & cabana', 'Library', 'Guest suite', 'Wine cellar'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'residential-4',
    imagePropertyType: 'residential',
    createdAt: '2026-02-08',
    viewCount: 1876,
    aiEstimatedValue: 920000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'res-005',
    title: 'West Loop Loft Penthouse',
    description: "Full-floor penthouse atop a converted warehouse in Chicago's West Loop. Soaring ceilings, exposed brick, private rooftop deck, concierge building with valet.",
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 750000,
    city: 'Chicago',
    state: 'IL',
    sqft: 2800,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2005,
    lotAcres: null,
    features: ['Rooftop deck', 'Exposed brick', 'Concierge', 'Valet parking'],
    isTokenized: true,
    tokenTotalSupply: 750,
    tokenAvailableSupply: 412,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 28,
    imageSlot: 'residential-5',
    imagePropertyType: 'residential',
    createdAt: '2026-01-30',
    viewCount: 2234,
    aiEstimatedValue: 780000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'res-006',
    title: 'Lakefront Family Home',
    description: 'Exceptional lakefront property with private dock, boat lift, and panoramic water views. Open-concept main floor, screened porch, three-car garage on 0.8 acres.',
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 540000,
    city: 'Nashville',
    state: 'TN',
    sqft: 3100,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 2001,
    lotAcres: 0.80,
    features: ['Private dock', 'Boat lift', 'Water views', '3-car garage'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'residential-1',
    imagePropertyType: 'residential',
    createdAt: '2026-01-18',
    viewCount: 1543,
    aiEstimatedValue: 558000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'res-007',
    title: 'Victorian South End Brownstone',
    description: "Meticulously restored 1890s brownstone. Original plaster medallions, mahogany millwork, chef's kitchen addition, private garden. Steps from Back Bay.",
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 980000,
    city: 'Boston',
    state: 'MA',
    sqft: 2650,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 1892,
    lotAcres: 0.06,
    features: ['Period details', "Chef's kitchen", 'Private garden', 'Parking'],
    isTokenized: true,
    tokenTotalSupply: 500,
    tokenAvailableSupply: 80,
    tokenPricePerFraction: 1960,
    tokenInvestorCount: 42,
    imageSlot: 'residential-2',
    imagePropertyType: 'residential',
    createdAt: '2026-01-05',
    viewCount: 3109,
    aiEstimatedValue: 1020000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'res-008',
    title: 'Desert Modern Estate',
    description: 'Award-winning desert modern architecture on 1.2 acres in Paradise Valley. Infinity pool, mountain views, 6-car garage, home theater, and private casita.',
    propertyType: 'RESIDENTIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 1100000,
    city: 'Scottsdale',
    state: 'AZ',
    sqft: 5200,
    bedrooms: 5,
    bathrooms: 5,
    yearBuilt: 2018,
    lotAcres: 1.20,
    features: ['Infinity pool', 'Mountain views', '6-car garage', 'Guest casita'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'residential-3',
    imagePropertyType: 'residential',
    createdAt: '2025-12-20',
    viewCount: 2891,
    aiEstimatedValue: 1075000,
    aiConfidence: 'MEDIUM',
  },

  // ── COMMERCIAL ─────────────────────────────────────────────────────────────
  {
    id: 'com-001',
    title: 'Class-A Downtown Office Suite',
    description: "Premier 14,000 sqft office space on the 22nd floor of Denver's most prestigious tower. Floor-to-ceiling windows, custom buildout, parking included.",
    propertyType: 'COMMERCIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 2100000,
    city: 'Denver',
    state: 'CO',
    sqft: 14000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2010,
    lotAcres: null,
    features: ['Floor-to-ceiling windows', 'Custom buildout', 'Parking included', 'Concierge lobby'],
    isTokenized: true,
    tokenTotalSupply: 2100,
    tokenAvailableSupply: 924,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 73,
    imageSlot: 'commercial-1',
    imagePropertyType: 'commercial',
    createdAt: '2026-02-28',
    viewCount: 3420,
    aiEstimatedValue: 2250000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'com-002',
    title: 'Waterfront NNN Retail Center',
    description: 'Eight-unit retail strip fully occupied by national credit tenants. NNN leases with 3% annual escalators. Cap rate: 6.8%. Minimal management required.',
    propertyType: 'COMMERCIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 1850000,
    city: 'Portland',
    state: 'OR',
    sqft: 11200,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 1998,
    lotAcres: 1.80,
    features: ['NNN leases', 'National tenants', '6.8% cap rate', 'Renovated 2022'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'commercial-2',
    imagePropertyType: 'commercial',
    createdAt: '2026-02-10',
    viewCount: 2150,
    aiEstimatedValue: 1920000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'com-003',
    title: 'Innovation Campus Complex',
    description: "Three-building tech campus totaling 48,000 sqft in Seattle's SLU innovation corridor. Long-term leases with Fortune 500 tenants. Adjacent to Amazon HQ.",
    propertyType: 'COMMERCIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 4500000,
    city: 'Seattle',
    state: 'WA',
    sqft: 48000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2014,
    lotAcres: 2.40,
    features: ['Fortune 500 tenants', 'Bike storage', 'EV charging', 'Conference center'],
    isTokenized: true,
    tokenTotalSupply: 4500,
    tokenAvailableSupply: 1800,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 112,
    imageSlot: 'commercial-3',
    imagePropertyType: 'commercial',
    createdAt: '2026-01-25',
    viewCount: 5810,
    aiEstimatedValue: 4750000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'com-004',
    title: 'Medical Office Professional Plaza',
    description: 'Purpose-built medical campus with 22 suites across two buildings. Currently 91% occupied. On-site lab, radiology suite, and pharmacy. Recession-proof tenant base.',
    propertyType: 'COMMERCIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 3200000,
    city: 'Houston',
    state: 'TX',
    sqft: 24500,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2007,
    lotAcres: 3.20,
    features: ['91% occupied', 'Radiology suite', 'Medical gas lines', 'Ample parking'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'commercial-4',
    imagePropertyType: 'commercial',
    createdAt: '2025-12-28',
    viewCount: 2340,
    aiEstimatedValue: 3380000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'com-005',
    title: 'Boutique Hotel Property',
    description: "48-key boutique hotel in San Diego's Gaslamp Quarter. Fully renovated 2023. STR license. Average ADR $285, 78% occupancy. Turn-key operation with experienced staff.",
    propertyType: 'COMMERCIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 5800000,
    city: 'San Diego',
    state: 'CA',
    sqft: 32000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 1972,
    lotAcres: 0.60,
    features: ['48 keys', 'Rooftop bar', 'Convention center adjacent', 'Renovated 2023'],
    isTokenized: true,
    tokenTotalSupply: 2000,
    tokenAvailableSupply: 1080,
    tokenPricePerFraction: 2900,
    tokenInvestorCount: 88,
    imageSlot: 'commercial-1',
    imagePropertyType: 'commercial',
    createdAt: '2025-12-15',
    viewCount: 6720,
    aiEstimatedValue: 6100000,
    aiConfidence: 'MEDIUM',
  },

  // ── LAND ───────────────────────────────────────────────────────────────────
  {
    id: 'land-001',
    title: 'Napa Valley Agricultural Parcel',
    description: 'Prime 22-acre agricultural parcel in the heart of Napa Valley. Established Cabernet Sauvignon vineyard with irrigation system. Long-term agricultural lease opportunity available.',
    propertyType: 'LAND',
    listingType: 'BOTH',
    status: 'ACTIVE',
    price: 890000,
    city: 'Napa',
    state: 'CA',
    sqft: 958320,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    lotAcres: 22.0,
    features: ['Established vineyard', 'Water rights', 'Agricultural zoning', 'Irrigation system'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'land-1',
    imagePropertyType: 'land',
    createdAt: '2026-02-18',
    viewCount: 1890,
    aiEstimatedValue: 940000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'land-002',
    title: 'East Austin Development Opportunity',
    description: "Shovel-ready 4.2-acre mixed-use site in Austin's fastest-growing corridor. Permits up to 8 stories. Two blocks from planned Red Line station. All utilities at site.",
    propertyType: 'LAND',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 1450000,
    city: 'Austin',
    state: 'TX',
    sqft: 182952,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    lotAcres: 4.20,
    features: ['Mixed-use zoning', 'Utilities at site', 'Transit adjacent', 'Graded & ready'],
    isTokenized: true,
    tokenTotalSupply: 1000,
    tokenAvailableSupply: 750,
    tokenPricePerFraction: 1450,
    tokenInvestorCount: 31,
    imageSlot: 'land-2',
    imagePropertyType: 'land',
    createdAt: '2026-02-05',
    viewCount: 3108,
    aiEstimatedValue: 1580000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'land-003',
    title: 'Beachfront Oceanside Lot',
    description: 'Rare oceanfront buildable lot on the Outer Banks. 120 feet of direct ocean frontage on 0.9 acres. Septic approval in place. Vacation rental zoning.',
    propertyType: 'LAND',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 750000,
    city: 'Kill Devil Hills',
    state: 'NC',
    sqft: 39204,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    lotAcres: 0.90,
    features: ['Ocean frontage', 'Septic approved', 'Buildable', 'VR zoning'],
    isTokenized: true,
    tokenTotalSupply: 500,
    tokenAvailableSupply: 200,
    tokenPricePerFraction: 1500,
    tokenInvestorCount: 26,
    imageSlot: 'land-3',
    imagePropertyType: 'land',
    createdAt: '2026-01-15',
    viewCount: 2780,
    aiEstimatedValue: 720000,
    aiConfidence: 'LOW',
  },
  {
    id: 'land-004',
    title: 'Montana Ranch Land — For Lease',
    description: '480 acres of productive Montana ranch land. Currently leased for cattle grazing. Spectacular mountain views, hunting rights, trophy elk and mule deer population.',
    propertyType: 'LAND',
    listingType: 'LEASE',
    status: 'ACTIVE',
    price: 2300000,
    city: 'Billings',
    state: 'MT',
    sqft: 20908800,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    lotAcres: 480.0,
    features: ['Cattle grazing', 'Hunting rights', 'Water rights', 'Road access'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'land-1',
    imagePropertyType: 'land',
    createdAt: '2025-12-10',
    viewCount: 1240,
    aiEstimatedValue: null,
    aiConfidence: null,
  },
  {
    id: 'land-005',
    title: 'Industrial Zoned Development Lot',
    description: "Rare 8-acre industrial-zoned parcel adjacent to DFW's logistics corridor. Heavy industrial permitted. Rail spur available. 5 miles from Dallas Fort Worth International Airport.",
    propertyType: 'LAND',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 620000,
    city: 'Plano',
    state: 'TX',
    sqft: 348480,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    lotAcres: 8.0,
    features: ['Heavy industrial zoning', 'Rail spur available', 'DFW adjacent', 'Utilities at road'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'land-2',
    imagePropertyType: 'land',
    createdAt: '2025-12-05',
    viewCount: 980,
    aiEstimatedValue: 650000,
    aiConfidence: 'MEDIUM',
  },

  // ── INDUSTRIAL ─────────────────────────────────────────────────────────────
  {
    id: 'ind-001',
    title: 'Last-Mile Logistics Hub',
    description: "State-of-the-art 68,000 sqft distribution center in Memphis's primary logistics corridor. 32' clear heights, 40 dock doors, ESFR sprinklers. 100% occupied — long-term NNN lease.",
    propertyType: 'INDUSTRIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 3800000,
    city: 'Memphis',
    state: 'TN',
    sqft: 68000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2017,
    lotAcres: 4.50,
    features: ["32' clear height", '40 dock doors', 'ESFR sprinklers', 'Long-term NNN lease'],
    isTokenized: true,
    tokenTotalSupply: 3800,
    tokenAvailableSupply: 1748,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 95,
    imageSlot: 'industrial-1',
    imagePropertyType: 'industrial',
    createdAt: '2026-02-24',
    viewCount: 4280,
    aiEstimatedValue: 4050000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'ind-002',
    title: 'Cold Storage Distribution Center',
    description: "Purpose-built cold storage facility with 41,000 sqft of temperature-controlled space. Multi-temp zones. Located in Chicago's O'Hare logistics submarket.",
    propertyType: 'INDUSTRIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 4100000,
    city: 'Chicago',
    state: 'IL',
    sqft: 41000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2020,
    lotAcres: 3.20,
    features: ['Multi-temp zones', 'Solar panels', 'Dock levelers', 'Fully occupied'],
    isTokenized: true,
    tokenTotalSupply: 2050,
    tokenAvailableSupply: 1128,
    tokenPricePerFraction: 2000,
    tokenInvestorCount: 67,
    imageSlot: 'industrial-2',
    imagePropertyType: 'industrial',
    createdAt: '2026-01-08',
    viewCount: 3120,
    aiEstimatedValue: 4350000,
    aiConfidence: 'HIGH',
  },
  {
    id: 'ind-003',
    title: 'Light Manufacturing Facility',
    description: 'Versatile 55,000 sqft light manufacturing facility with high-bay production floor, 5,000 sqft of office, loading dock, and heavy 3-phase power (2,000 amp service).',
    propertyType: 'INDUSTRIAL',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 2900000,
    city: 'Detroit',
    state: 'MI',
    sqft: 55000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 1995,
    lotAcres: 6.10,
    features: ['High-bay production', 'Heavy power', 'Loading dock', 'Renovated 2021'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'industrial-1',
    imagePropertyType: 'industrial',
    createdAt: '2025-11-15',
    viewCount: 1456,
    aiEstimatedValue: 2750000,
    aiConfidence: 'MEDIUM',
  },

  // ── MIXED USE ──────────────────────────────────────────────────────────────
  {
    id: 'mix-001',
    title: 'Live/Work Arts District Lofts',
    description: "Eight-unit mixed-use building in Brooklyn's Bushwick Arts District. Ground floor: 4,000 sqft commercial. Upper floors: 7 loft residences (avg 1,400 sqft). High demand location.",
    propertyType: 'MIXED_USE',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 2200000,
    city: 'Brooklyn',
    state: 'NY',
    sqft: 13800,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 1960,
    lotAcres: 0.18,
    features: ['Ground floor retail', '7 residential lofts', 'Exposed brick', 'Renovated 2019'],
    isTokenized: true,
    tokenTotalSupply: 2200,
    tokenAvailableSupply: 924,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 81,
    imageSlot: 'mixed-1',
    imagePropertyType: 'mixed',
    createdAt: '2026-02-12',
    viewCount: 3890,
    aiEstimatedValue: 2380000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'mix-002',
    title: 'Pearl District Mixed-Use Tower',
    description: "Seven-story development in Portland's coveted Pearl District. Ground floor restaurant and retail (7,200 sqft), five stories of premium apartments (24 units), rooftop amenity deck.",
    propertyType: 'MIXED_USE',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 3500000,
    city: 'Portland',
    state: 'OR',
    sqft: 31000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2016,
    lotAcres: 0.22,
    features: ['24 apartments', 'Ground floor retail', 'Rooftop deck', 'EV charging'],
    isTokenized: true,
    tokenTotalSupply: 3500,
    tokenAvailableSupply: 2555,
    tokenPricePerFraction: 1000,
    tokenInvestorCount: 44,
    imageSlot: 'mixed-1',
    imagePropertyType: 'mixed',
    createdAt: '2025-12-22',
    viewCount: 2760,
    aiEstimatedValue: 3650000,
    aiConfidence: 'MEDIUM',
  },
  {
    id: 'mix-003',
    title: 'Adaptive Reuse Historic Mill',
    description: "Stunning conversion of an 1887 textile mill into 18,000 sqft of premium office and event space. Original exposed granite walls, timber beams. Fully leased to creative agencies.",
    propertyType: 'MIXED_USE',
    listingType: 'BUY',
    status: 'ACTIVE',
    price: 1900000,
    city: 'Providence',
    state: 'RI',
    sqft: 18000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 1887,
    lotAcres: 0.70,
    features: ['Historic designation', 'Full occupancy', 'Event venue', 'Original millwork'],
    isTokenized: false,
    tokenTotalSupply: null,
    tokenAvailableSupply: null,
    tokenPricePerFraction: null,
    tokenInvestorCount: null,
    imageSlot: 'mixed-1',
    imagePropertyType: 'mixed',
    createdAt: '2025-11-28',
    viewCount: 1920,
    aiEstimatedValue: 2050000,
    aiConfidence: 'LOW',
  },
]

// ---------------------------------------------------------------------------
// Derived constants — computed once at module level
// ---------------------------------------------------------------------------

export const MARKETPLACE_STATS = {
  totalActive: MOCK_LISTINGS.filter((l) => l.status === 'ACTIVE').length,
  tokenizedCount: MOCK_LISTINGS.filter((l) => l.isTokenized).length,
  landCount: MOCK_LISTINGS.filter((l) => l.propertyType === 'LAND').length,
  totalValue: MOCK_LISTINGS.reduce((sum, l) => sum + l.price, 0),
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function formatPrice(price: number): string {
  if (price >= 1_000_000) {
    const m = price / 1_000_000
    const formatted = m % 1 === 0 ? m.toFixed(0) : parseFloat(m.toFixed(2)).toString()
    return `$${formatted}M`
  }
  return `$${Math.round(price / 1000)}K`
}

export function tokenSoldPercent(listing: MockListing): number {
  if (!listing.tokenTotalSupply || listing.tokenAvailableSupply === null) return 0
  const sold = listing.tokenTotalSupply - listing.tokenAvailableSupply
  return Math.round((sold / listing.tokenTotalSupply) * 100)
}
